/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_ThreatNodeDialog (void)
{
  GtkWidget *ThreatNodeDialog;
  GdkPixbuf *ThreatNodeDialog_icon_pixbuf;
  GtkWidget *vbox1;
  GtkWidget *hbox1;
  GtkWidget *nameLabel;
  GtkWidget *nameCtrl;
  GtkWidget *hbox2;
  GtkWidget *methodLabel;
  GtkWidget *methodCtrl;
  GtkWidget *hbox3;
  GtkWidget *likelihoodLabel;
  GtkWidget *likelihoodCtrl;
  GtkWidget *okButton;

  ThreatNodeDialog = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (ThreatNodeDialog), _("Threat Properties"));
  gtk_window_set_modal (GTK_WINDOW (ThreatNodeDialog), TRUE);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (ThreatNodeDialog), TRUE);
  ThreatNodeDialog_icon_pixbuf = create_pixbuf ("threats.gif");
  if (ThreatNodeDialog_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (ThreatNodeDialog), ThreatNodeDialog_icon_pixbuf);
      gdk_pixbuf_unref (ThreatNodeDialog_icon_pixbuf);
    }

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (ThreatNodeDialog), vbox1);

  hbox1 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox1);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox1, TRUE, TRUE, 0);

  nameLabel = gtk_label_new (_("Name"));
  gtk_widget_show (nameLabel);
  gtk_box_pack_start (GTK_BOX (hbox1), nameLabel, FALSE, FALSE, 0);

  nameCtrl = gtk_entry_new ();
  gtk_widget_show (nameCtrl);
  gtk_box_pack_start (GTK_BOX (hbox1), nameCtrl, TRUE, TRUE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (nameCtrl), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (nameCtrl), 8226);

  hbox2 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox2);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox2, TRUE, TRUE, 0);

  methodLabel = gtk_label_new (_("Method"));
  gtk_widget_show (methodLabel);
  gtk_box_pack_start (GTK_BOX (hbox2), methodLabel, FALSE, FALSE, 0);

  methodCtrl = gtk_entry_new ();
  gtk_widget_show (methodCtrl);
  gtk_box_pack_start (GTK_BOX (hbox2), methodCtrl, TRUE, TRUE, 0);
  gtk_widget_set_size_request (methodCtrl, 160, 60);
  gtk_editable_set_editable (GTK_EDITABLE (methodCtrl), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (methodCtrl), 8226);

  hbox3 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox3);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox3, TRUE, TRUE, 0);

  likelihoodLabel = gtk_label_new (_("Likelihood"));
  gtk_widget_show (likelihoodLabel);
  gtk_box_pack_start (GTK_BOX (hbox3), likelihoodLabel, FALSE, FALSE, 0);

  likelihoodCtrl = gtk_entry_new ();
  gtk_widget_show (likelihoodCtrl);
  gtk_box_pack_start (GTK_BOX (hbox3), likelihoodCtrl, TRUE, TRUE, 0);
  gtk_editable_set_editable (GTK_EDITABLE (likelihoodCtrl), FALSE);
  gtk_entry_set_invisible_char (GTK_ENTRY (likelihoodCtrl), 8226);

  okButton = gtk_button_new_with_mnemonic (_("Ok"));
  gtk_widget_show (okButton);
  gtk_box_pack_start (GTK_BOX (vbox1), okButton, FALSE, FALSE, 0);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (ThreatNodeDialog, ThreatNodeDialog, "ThreatNodeDialog");
  GLADE_HOOKUP_OBJECT (ThreatNodeDialog, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (ThreatNodeDialog, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (ThreatNodeDialog, nameLabel, "nameLabel");
  GLADE_HOOKUP_OBJECT (ThreatNodeDialog, nameCtrl, "nameCtrl");
  GLADE_HOOKUP_OBJECT (ThreatNodeDialog, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (ThreatNodeDialog, methodLabel, "methodLabel");
  GLADE_HOOKUP_OBJECT (ThreatNodeDialog, methodCtrl, "methodCtrl");
  GLADE_HOOKUP_OBJECT (ThreatNodeDialog, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (ThreatNodeDialog, likelihoodLabel, "likelihoodLabel");
  GLADE_HOOKUP_OBJECT (ThreatNodeDialog, likelihoodCtrl, "likelihoodCtrl");
  GLADE_HOOKUP_OBJECT (ThreatNodeDialog, okButton, "okButton");

  return ThreatNodeDialog;
}

