#$URL: svn://edison.comlab.ox.ac.uk/res08/iris/iris/DimensionNameIdentifier.py $ $Id: DimensionNameIdentifier.py 387 2011-01-03 23:12:51Z shaf $
import ARM

def dimensionName(className):
  if (className == 'AttackersDialog'):  return 'attacker'
  if (className == 'AssetsDialog'): return 'asset'
  if (className == 'TemplateAssetsDialog'): return 'template_asset'
  if (className == 'SecurityPatternsDialog'): return 'securitypattern'
  if (className == 'ClassAssociationsDialog'): return 'classassociation'
  if (className == 'GoalAssociationsDialog'): return 'goalassociation'
  if (className == 'GoalsDialog'): return 'goal'
  if (className == 'ObstaclesDialog'): return 'obstacle'
  if (className == 'ThreatsDialog'): return 'threat'
  if (className == 'VulnerabilitiesDialog'): return 'vulnerability'
  if (className == 'RisksDialog'): return 'risk'
  if (className == 'ResponsesDialog'): return 'response'
  if (className == 'CountermeasuresDialog'): return 'countermeasure'
  if (className == 'TracesDialog'): return 'trace'
  if (className == 'TasksDialog'): return 'task'
  if (className == 'UseCasesDialog'): return 'usecase'
  if (className == 'PersonasDialog'): return 'persona'
  if (className == 'EnvironmentsDialog'): return 'environment'
  if (className == 'RolesDialog'): return 'role'
  if (className == 'ResponsibilitiesDialog'): return 'responsibility'
  if (className == 'DomainPropertiesDialog'): return 'domainproperty'
  if (className == 'DomainsDialog'): return 'domain'
  if (className == 'ValueTypesDialog'): return 'value_type'
  if (className == 'DependenciesDialog'): return 'dependencyassociation'
  if (className == 'ExternalDocumentsDialog'): return 'external_document'
  if (className == 'DocumentReferencesDialog'): return 'document_reference'
  if (className == 'PersonaCharacteristicsDialog'): return 'persona_characteristic'
  if (className == 'TaskCharacteristicsDialog'): return 'task_characteristic'
  if (className == 'BehaviouralCharacteristicsDialog'): return 'persona_characteristic'
  if (className == 'ConceptReferencesDialog'): return 'concept_reference'
  raise ARM.UnknownDialogClass(className)
